version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: bitlab-postgres
    restart: always
    environment:
      POSTGRES_DB: bitlab_db
      POSTGRES_USER: bitlab
      POSTGRES_PASSWORD: bitlab123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mainservice:
    image: kristinaunguryanu/mainservice:latest
    container_name: mainservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bitlab_db
      SPRING_DATASOURCE_USERNAME: bitlab
      SPRING_DATASOURCE_PASSWORD: bitlab123
    depends_on:
      - postgres

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db-container-internship
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    volumes:
      - keycloak_data:/var/lib/postgresql/data
      - ./insert.sql:/docker-entrypoint-initdb.d/insert.sql:ro
    ports:
      - 2345:5432

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: pass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --http-relative-path=/auth
      - --spi-converter-javascript-enabled=true
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-db

volumes:
  postgres_data:
  keycloak_data:
